### ISSUE TITLE
Platform plugin error on install

### ISSUE THREAD

**Issue by cantaylancapraz** [epi2me-labs/labslauncher#9]
Hi,

I'm trying to install launcher without downloading launcher file. I followed following steps from readme
- git clone https://github.com/epi2me-labs/labslauncher.git
- cd labslauncher
- PYTHON=python3 make run

And I got following error. Do you have any recommendation?
```
Cannot load library /usr/local/bin/EPI2ME-Labs-Launcher/PyQt5/Qt/plugins/platforms/libqxcb.so: (libxcb-icccm.so.4: cannot open shared object file: No such file or directory)
QLibraryPrivate::loadPlugin failed on "/usr/local/bin/EPI2ME-Labs-Launcher/PyQt5/Qt/plugins/platforms/libqxcb.so" : "Cannot load library /usr/local/bin/EPI2ME-Labs-Launcher/PyQt5/Qt/plugins/platforms/libqxcb.so: (libxcb-icccm.so.4: cannot open shared object file: No such file or directory)"
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.


```

**Comment by cjw85** [comment]
@cantaylancapraz for reference since I think you are using other methods now.

Can you indicate on what platform you are running (some flavour of linux I presume)?

If so, you can look [here](https://github.com/epi2me-labs/labslauncher/blob/master/.gitlab-ci.yml#L20) or [here](https://github.com/epi2me-labs/labslauncher/blob/master/.gitlab-ci.yml#L25) to see how we prepare Ubuntu (Debian-based) and CentOS (Redhat) environments for building and testing the binary packages.
